services:
  backend:
    build: ./backend
    container_name: whatsapp_backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    restart: unless-stopped
    networks:
      - whatsapp-net

  frontend:
    build: ./frontend
    container_name: whatsapp_frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - whatsapp-net

  nginx:
    image: nginx:alpine
    container_name: whatsapp_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/technologygroup.es/technologygroup.es.fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/technologygroup.es/technologygroup.es.key.pem:/etc/nginx/ssl/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - whatsapp-net
      
networks:
  whatsapp-net: