version: '3.8'

services:
  backend:
    build: ./backend
    container_name: whatsapp_backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: whatsapp_frontend
    ports:
      - "3002:80"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: whatsapp_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
