services:
  backend:
    build: ./backend
    container_name: whatsapp_backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=3001
    restart: unless-stopped
    networks:
      - whatsapp-net
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: whatsapp_frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - whatsapp-net

  nginx:
    image: nginx:alpine
    container_name: whatsapp_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/technologygroup.es/technologygroup.es.fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/technologygroup.es/technologygroup.es.key.pem:/etc/nginx/ssl/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - whatsapp-net

  db:
    image: postgres:15
    container_name: whatsapp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: whatsapp_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - whatsapp-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: whatsapp_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tg.es
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "5050:80"
    networks:
      - whatsapp-net

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - whatsapp-net

  worker:
    build: ./backend
    command: node src/workers/worker.js
    depends_on:
      - redis
      - backend
    networks:
      - whatsapp-net
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  whatsapp-net:


volumes:
  pgdata:
